{
 "title": "Kafka",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  {
   "title": "Producer Request Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Outgoing Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_producer_outgoing_byte_rate{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Record Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_producer_record_send_rate{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kafka_producer_request_rate{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Records Per Request Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "kafka_producer_records_per_request_avg {application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Request Size Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "kafka_producer_request_size_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Batch Size Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "kafka_producer_batch_size_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Record Queue Time Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "kafka_producer_record_queue_time_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Bufferpool Wait Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "kafka_producer_bufferpool_wait_ratio{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Buffer Available Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "kafka_producer_buffer_available_bytes{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Rate Compression Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "kafka_producer_compression_rate_avg {application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Poll Idle Ratio Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "kafka_consumer_poll_idle_ratio_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Avg Time Between Poll",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "kafka_consumer_time_between_poll_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Max Time Between Poll",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "kafka_consumer_time_between_poll_max{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}